# Multidimesional Arrays
## Its a list in a list of lists...
An array having more than two dimensions is called a multidimensional array.

You can access a two-dimensional matrix element with two subscripts: the first representing the row index, and the second representing the column index.
   ![1](https://www.mathworks.com/help/matlab/math/ch_data_struct3.gif)
Multidimensional arrays use additional subscripts for indexing. A three-dimensional array, for example, uses three subscripts
![2](https://www.mathworks.com/help/matlab/math/ch_data_struct4.gif)

- The first references array dimension 1, the row.
- The second references dimension 2, the column.
- The third references dimension 3.
    
    
This illustration uses the concept of a page to represent dimensions 3 and higher.

To access the element in the second row, third column of page 2, for example, you use the subscripts (2,3,2).
<br>
<br>
## Setting up

In [1]:
##the same printsum function from yesterday
function printsum(a)
    # summary:: Generates a summary of an object
    println(summary(a), ": ", repr(a))
end

printsum (generic function with 1 method)

## Initialising n-dimensional arrays
Many functions for constructing and initializing arrays are provided. In the following list of such functions, calls with a dims... argument can either take a single tuple of dimension sizes or a series of dimension sizes passed as a variable number of arguments. Most of these functions also accept a first input T, which is the element type of the array. If the type T is omitted it will default to Float64.
<br>
```Function```	Description
<br>
```Array{T}(dims...)```	an uninitialized dense Array
<br>
```zeros(T, dims...)```	an Array of all zeros
<br>
```zeros(A)```	an array of all zeros with the same type, element type and shape as A
<br>
```ones(T, dims...)```	an Array of all ones
<br>
```ones(A)```	an array of all ones with the same type, element type and shape as A
<br>
```trues(dims...)```	a BitArray with all values true
<br>
```trues(A)```	a BitArray with all values true and the same shape as A
<br>
```falses(dims...)```	a BitArray with all values false
<br>
```falses(A)```	a BitArray with all values false and the same shape as A
<br>
```reshape(A, dims...)```	an array containing the same data as A, but with different dimensions
<br>
```copy(A)```	copy A
<br>
```deepcopy(A)```	copy A, recursively copying its elements
<br>
```similar(A, T, dims...)```	an uninitialized array of the same type as A (dense, sparse, etc.), but with the specified element type and dimensions. The second and third arguments are both optional, defaulting to the element type and dimensions of A if omitted.
<br>
```reinterpret(T, A)```	an array with the same binary data as A, but with element type T
<br>
```rand(T, dims...)```	an Array with random, iid and uniformly distributed values in the half-open interval 0,1
<br>
```randn(T, dims...)```	an Array with random, iid and standard normally distributed values
<br>
```eye(T, n)```	n-by-n identity matrix
<br>
```eye(T, m, n)```	m-by-n identity matrix
<br>
```linspace(start, stop, n)```	range of n linearly spaced elements from start to stop
<br>
```fill!(A, x)```	fill the array A with the value x
<br>
```fill(x, dims...)```	an Array filled with the value x
<br>
<br>
## So lets try some of these out and make some arrays!

In [10]:
# repeat can be useful to expand a grid
# as in R's expand.grid() function
a = repeat([1,2],inner=[1],outer=[3*2])
b = repeat([1,2,3],inner=[2],outer=[2])
c = repeat([1,2,3,4],inner=[3],outer=[1])
printsum(a)
printsum(b)
printsum(c)

#now lets add them all together with hcat (horizontal concatation)
m1 = [a b c]
printsum(m1)

12-element Array{Int64,1}: [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]
12-element Array{Int64,1}: [1, 1, 2, 2, 3, 3, 1, 1, 2, 2, 3, 3]
12-element Array{Int64,1}: [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]
12×3 Array{Int64,2}: [1 1 1; 2 1 1; 1 2 1; 2 2 2; 1 3 2; 2 3 2; 1 1 3; 2 1 3; 1 2 3; 2 2 4; 1 3 4; 2 3 4]


In [7]:
#for simple repetitions of arrays, 
#use repmat

# replicate m1 once into dim1 and twice into dim2
m2 = repmat(m1,1,2) 
printsum(m2)

#replicate m1 twice into dim1 and once into dim2
m3 = repmat(m1,2,1)   
printsum(m3)

12×6 Array{Int64,2}: [1 1 1 1 1 1; 2 1 1 2 1 1; 1 2 1 1 2 1; 2 2 2 2 2 2; 1 3 2 1 3 2; 2 3 2 2 3 2; 1 1 3 1 1 3; 2 1 3 2 1 3; 1 2 3 1 2 3; 2 2 4 2 2 4; 1 3 4 1 3 4; 2 3 4 2 3 4]
24×3 Array{Int64,2}: [1 1 1; 2 1 1; 1 2 1; 2 2 2; 1 3 2; 2 3 2; 1 1 3; 2 1 3; 1 2 3; 2 2 4; 1 3 4; 2 3 4; 1 1 1; 2 1 1; 1 2 1; 2 2 2; 1 3 2; 2 3 2; 1 1 3; 2 1 3; 1 2 3; 2 2 4; 1 3 4; 2 3 4]


note how the output is showing how many dimensions there are in the show() function
<br>
>24×3 Array{Int64,2}

In [26]:
#lets go to the next dimesion
m3 = rand(9,3,3)
printsum(m3)

#and the next
m4 = randn(12,2,4)
printsum(m4)

9×3×3 Array{Float64,3}: [0.401433 0.618003 0.69213; 0.108288 0.404777 0.154103; 0.471791 0.483503 0.411998; 0.208856 0.489068 0.676091; 0.714079 0.495382 0.351403; 0.433026 0.929933 0.702046; 0.626158 0.315136 0.0609321; 0.14459 0.113526 0.315764; 0.0327673 0.818828 0.795003]

[0.846858 0.0271667 0.61899; 0.170805 0.815663 0.079799; 0.830743 0.506352 0.669182; 0.444768 0.910432 0.82389; 0.327489 0.180957 0.820432; 0.569912 0.00202483 0.237028; 0.37433 0.263044 0.603121; 0.288602 0.680032 0.350542; 0.933075 0.188174 0.75294]

[0.244846 0.212927 0.51331; 0.1185 0.201512 0.140059; 0.754334 0.134866 0.753388; 0.305591 0.0796685 0.253984; 0.147096 0.833068 0.440506; 0.858083 0.2902 0.00475607; 0.98081 0.262119 0.140841; 0.38791 0.37327 0.672221; 0.725935 0.888978 0.306427]
12×2×4 Array{Float64,3}: [0.338419 -1.65065; -0.00231605 0.252076; 0.792234 0.29226; -1.40075 -0.327944; 0.59852 1.56699; 2.15615 0.169927; -0.790463 -0.493216; -0.347925 0.0708134; 0.33639 0.619957; -0.256256 -0.34015; -

In [44]:
#Yay, just answered my first question on 
#stack overflow with this!
#https://stackoverflow.com/a/46689828/6372042
a = [2,3]

#hcat
b = [[2, 3] [4, 5]]
printsum(b)

#vcat
c = [[2 3] ; [4 5]]
printsum(c)

2×2 Array{Int64,2}: [2 4; 3 5]
2×2 Array{Int64,2}: [2 3; 4 5]


In [46]:
#lets create a multi array with list comprehensions
#each argument will create a new dimension
m5 = String["Hi Im element # $(i+2*(j-1 + 3*(k-1)))" for i=1:2, j=1:3, k=1:2]
printsum(m5)

2×3×2 Array{String,3}: String["Hi Im element # 1" "Hi Im element # 3" "Hi Im element # 5"; "Hi Im element # 2" "Hi Im element # 4" "Hi Im element # 6"]

String["Hi Im element # 7" "Hi Im element # 9" "Hi Im element # 11"; "Hi Im element # 8" "Hi Im element # 10" "Hi Im element # 12"]
